"""Type stubs for esp32 module"""
def wake_on_touch(wake: bool) -> None: ...
def wake_on_ext0(pin: int, level: int) -> None: ...
def wake_on_ext1(pins: list, level: int) -> None: ...
# Add other functions as needed